version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/visits_control
      JWT_SECRET: ${JWT_SECRET:-change_me_super_secure}
      JWT_EXPIRES_IN: 1d
      CORS_ORIGIN: http://localhost:5173
    ports:
      - '4000:4000'

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - '5173:80'

volumes:
  mongo_data:
